== Detecting Jailbroken Device

[discrete]
=== Problem

You want to detect whether the device your app is running on is Jailbroken or rooted.

[discrete]
=== Solution

While there is no way to know whether the device is rooted with 100% certainty, you can use the https://github.com/shannah/CN1JailbreakDetect[CN1JailbreakDetect] cn1lib to to make a good guess.  This cn1lib acts as a thin wrapper around the https://github.com/scottyab/rootbeer[RootBeer] Android library, and https://github.com/thii/DTTJailbreakDetection[DTTJailbreakDetection] iOS library, which employ heuristics to determine whether the device has likely been jailbroken.



**Example**

[source,java]
----
package com.codename1.samples;


import com.codename1.ext.jailbreak.JailbreakDetect;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.codename1.ui.Button;
import com.codename1.ui.Command;


public class JailbreakDetectionSample {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Jailbreak Detection", BoxLayout.y());
        Button detect = new Button("Detect Jailbreak");
        detect.addActionListener(evt->{
            if (JailbreakDetect.isJailbreakDetectionSupported()) {
                if (JailbreakDetect.isJailbroken()) {
                    Dialog.show("Jailbroken","This device is jailbroken", new Command("OK") );
                } else {
                    Dialog.show("Not Jailbroken", "Probably not jailbroken.  But can't be 100% sure.", new Command("OK"));
                }
            } else {
                Dialog.show("No Idea", "No support for jailbreak detection on this device.", new Command("OK"));
            }
        });
        hi.add(detect);
        hi.show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}

----

TIP: This sample is part of the https://github.com/codenameone/CodenameOne/tree/master/Samples[Codename One samples] project, and can be run directly from the Codename One SampleRunner. 

[discrete]
=== Discussion

The https://github.com/shannah/CN1JailbreakDetect[CN1JailbreakDetect] provides two useful static methods for jailbreak detection:

. `isJailbreakDetectionSupported()` - This checks if the jailbreak detection is even supported on this platform.
. `isJailBroken()` - This checks if the device is jailbroken.  If detection is not supported, then this will always return `false`.

Currently jailbreak detection is only supported on Android and iOS.

IMPORTANT: There is NO way to know with 100% certainty whether or not a device has been jailbroken.  

[discrete]
=== Further Reading

. https://github.com/shannah/CN1JailbreakDetect[CN1JailbreakDetect github project] 
. https://github.com/scottyab/rootbeer[RootBeer project] (Used on Android)
. https://github.com/thii/DTTJailbreakDetection[DTTJailbreakDetection project] (Used on iOS)