== Deploying as a "Headless" Javascript App

[discrete]
=== Problem

You want to deploy your app inside a webpage "headlessly".  I.e. You don't want the user to see the app.  This might be useful if you just want to use your app as a javascript library.

[discrete]
=== Solution

Embed the app inside a 1-pixel iframe.

[source,html]
----
<!doctype html>
<html>
  <head> ... </head>
  <body>
    <iframe 
      id='myapp' 
      style='position:fixed; width: 1px; height:1px; border:none; bottom:0'
      src='https://example.com/MyApp/index.html'
    />
    .. Rest of webpage..
  </body>
</html>
----

NOTE: By trial and error, we have determined that displaying the iframe with 1px width and height is the best solution.  Using `display:none` causes the browser to not load the iframe at all.  Positioning the iframe outside the viewport, causes some APIs to be turned off (e.g. microphone).

[discrete]
=== Discussion

If you are deploying your app as a headless app, then you are likely expecting to be able to communicate between the webpage and your app.  You will also need to be notified of lifecycle events in your app so you know when it has finished loading.  Be aware of CORS (cross-origin-resource-sharing) browser policies if the page containing the `<iframe>` is loaded from a different domain than your app.

[discrete]
==== CORS Checklist

If the app (inside the iframe) is hosted at a different domain than the parent page (the page with the <iframe> tag), then you need to jump through some hoops to get things working.

1. Make sure that you are not sending the https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options[X-Frame-Options] response header with your app.  This header prevents your page from being displayed inside an iframe.  Many web hosts add this header automatically.
2. If you want to use features like "camera" and "microphone", you'll need to add the "allow" attribute to your iframe tag.  E.g. `<iframe allow="camera;microphone" .../>`.  For more information about this attribute, see https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes[This article].
3. If you need to communicate between the parent window and the iframe document (i.e. the window with your app, you'll need to use https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage[Window.postMessage()].  You can access the iframe's "window" object using `myIframe.contentWindow`.
