== Sending Messages to Outside Webpage

[discrete]
=== Problem

You want to send a message from your Codename One app to the webpage that contains it.

[discrete]
=== Solution

You can use `CN.postMessage()`, in Codename One to send the message.  The message will be dispatched to Javascript event listeners in the outside webpage that register to receive `cn1outbox` events.

.Sending a message from Codename One to the outside webpage.
[source,java]
----
// The Java side
MessageEvent message = new MessageEvent(
    null,        // event source... we'll leave it null
    "Hello",     // The message to deliver
    0            // Optional message code.  
);
//Dispatch the message
CN.postMessage(message);
----

.Receiving messages from Codename One in outside webpage.
[source,javascript]
----
// The javascript side
window.addEventListener('cn1outbox', function(evt) {
    var message = evt.detail;
    var code = evt.code;
    ...
});
----

[discrete]
=== Discussion

The `CN.postMessage()` method allows you to send a message to the native platform.  When deploying as a Javascript app, these messages are converted to custom DOM events and dispatched on the `window` object.  The event name is "cn1outbox", so you can receive events like this from the "javascript" side by registering an event listener for these types of events on the `window` object.

