== Parsing HTML

[discrete]
=== Problem

You want to parse some HTML content into a data structure.  You can't simply use the https://www.codenameone.com/javadoc/com/codename1/xml/XMLParser.html[XMLParser] class because the content is not well-formed XML, but you would like to be able to work with the parsed document using the same tools (e.g. https://www.codenameone.com/javadoc/com/codename1/processing/Result.html[Result] and https://www.codenameone.com/javadoc/com/codename1/xml/Element.html[Element].

[discrete]
=== Solution

Use the HTMLParser class from the https://github.com/shannah/CN1HTMLParser[CN1HTMLParser cn1lib].  It contains a simple API for parsing an HTML string into an https://www.codenameone.com/javadoc/com/codename1/xml/Element.html[Element], the same type of element that https://www.codenameone.com/javadoc/com/codename1/xml/XMLParser.html[XMLParser] returns.

Usage example:

[source,java]
----
HTMLParser parser = new HTMLParser();

Element root = parser.parse(htmlString).get(); <1>
Result r = Result.fromContent(root);

// Now modify the document
// In this example we're going to replace image src with placeholders
// so we can load them separately.
List<Element> images = r.getAsArray("//img");
int index = 0;
List<String> toLoad = new ArrayList<>();
if (images != null) {
    for (Element img : images) {
        String src = img.getAttribute("src");
        if (src.startsWith("http://*/") || (!src.startsWith("http://") && !src.startsWith("data:") && !src.startsWith("https"))) {
            img.setAttribute("id", "nt-image-"+index);
            toLoad.add(src);
            img.setAttribute("src", "");
            index++;
        }
    }
}

// Now write the document as well-formed XML.
XMLWriter writer = new XMLWriter(true);
String pageContent = writer.toXML(root);
----
<1> The `parse()` method returns an Async promise.  If you want to use it synchronously, you can call `get()`, which will wait until parsing is done.

**Alternate Async Usage**

The above example uses the `get()` method to wait until the result is ready, but you can use the parser asynchronously as well:

[source,java]
----
parser.parse(htmlString).ready(root->{
     // root is the root Element of the document.
});
----

[discrete]
=== Discussion

The HTMLParser class wraps an off-screen BrowserComponent to use the platform's native webview to actually parse the HTML.  It then serializes the DOM as XML, which is then re-parsed using the Codename One XML parser.  There are pitfalls to this approach, including performance (it takes time to pass data back-and forth between a webview, after all), and possibly different results on different platforms.

NOTE: The Codename One core library also includes an HTMLParser class at `com.codename1.ui.html.HTMLParser`.  This parser is meant to be used as part of the deprecated HTMLComponent class, which is a light-weight web view component that used to be used on platforms that didn't have a native webview, e.g. J2ME.  Now all modern platforms have a native webview, so this component isn't used much.  Additionally the HTMLParser class in that package doesn't support all HTML, and will fail in strange ways if you try to use it headlessly.

[discrete]
=== Further Reading

. https://www.codenameone.com/javadoc/com/codename1/xml/XMLParser.html[XMLParser Javadocs] - Since the output of HTMLParser is the same as XMLParser, you can find some useful examples in the XMLParser javadocs.

. 